# Generated by Django 5.1.7 on 2025-03-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('BR', 'Brasileiro'), ('US', 'Americano'), ('CA', 'Canadense'), ('FR', 'Francês'), ('DE', 'Alemão'), ('IT', 'Italiano'), ('ES', 'Espanhol'), ('PT', 'Português'), ('JP', 'Japonês'), ('CN', 'Chinês'), ('IN', 'Indiano'), ('RU', 'Russo'), ('AU', 'Australiano'), ('AR', 'Argentino'), ('MX', 'Mexicano'), ('GB', 'Britânico'), ('ZA', 'Sul-Africano'), ('KR', 'Sul-Coreano'), ('NL', 'Holandês'), ('CH', 'Suíço')], max_length=100, null=True)),
            ],
        ),
    ]
