# Generated by Django 5.1.7 on 2025-03-13 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='nome',
            new_name='name',
        ),
    ]
